name: Shipp it baby

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    env:
      working-directory: ./demos/vue
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            demos/vue/package-lock.json

      - name: Install and build extension
        run: npm ci && npm run build && npm test

      - name: Install demo dependencies
        run: npm ci
        working-directory: ${{env.working-directory}}

      - name: Build 🔧
        run: npm run build
        working-directory: ${{env.working-directory}}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./demos/vue/dist # The folder the action should deploy.
